### ISSUE TITLE
Unifying the description to one standard

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/usage-parser#134]
All of CLI describe a arguments with comma and of line or text in uppercase

I suggest to unifying the description, to this rules: 
- First litter is capital letter
- Text in lowercase
- Without comma and of line

**Comment by ifedchankau** [comment]
I think there is no need to transfer all text to lowercase, because there are many cases when capitalized letters are better.

Examples:
*```Lint code provided on <STDIN>```
*```Don't enforce ES2015+ rules```
*```Ignore unchanged lines (affects Travis only)```
*```Comma-separated list of disabled lint problem IDs```

**Comment by romanrostislavovich** [comment]
@Arcle1 I agree :)
