### ISSUE TITLE
Extra characters in default value

### ISSUE THREAD

**Issue by ifedchankau** [linterhub/usage-parser#154]
Sometimes, default value may be written as:
*`"table"`
*`'bower_components'`
*`[]`

In first two cases, default be cointain extra quotes, in third case default will be `[`. Please, fix it.

**Comment by romanrostislavovich** [comment]
I think we need to identity type  of properties before remove quotes. Because if it's string, we non to remove quotes

**Comment by ifedchankau** [comment]
@svoboda-rabstvo no, this issue about **additional** quotes which will be added to string in quotes.  So, first 2 cases in result JSON-file will be:
* `"default": "\"table\""`
* `"default": "\'bower_components\'"`

**Comment by romanrostislavovich** [comment]
Yes, but I suggest to remove `additional` and single quotes later, when we know a type of property. Because some default will be: `"2"` or `"false"`

**Comment by ifedchankau** [comment]
@svoboda-rabstvo good proposal, but, i think it is related to #151.

**Comment by romanrostislavovich** [comment]
@Arcle1 Yes, we need to find implementation for both issue :)
