### ISSUE TITLE
Add packages tests with gulp

### ISSUE THREAD

**Issue by ifedchankau** [linterhub/usage-parser#47]
Please, add packages tests (one valid and one failing) with gulp. Tests should be:
* get helps of packages from given array of package names (with help of npx)
* send this helps to parser() and parse it
* with the help of gulp, identify, if parsing is clear or it is failing and print errors

**Comment by ifedchankau** [comment]
@svoboda-rabstvo @xferra help, how we can do p.3? (identifying with gulp, if function is working clear or it is failing with exeception)

**Comment by xferra** [comment]
@Arcle1 How about specialised frameworks for that (unit tests), like mocha, etc.?

**Comment by ifedchankau** [comment]
@xferra integration tests, not unit. Parser is too small for unit tests. 

Now i almost done with gulp, but still don't know how to check if function working or failing.
In exist code (linterhub/schema) it is checking for the validation of json with `const result = validator.validate(data, schema.$schema.$ref);`. I need to ckeck js function, how can i do that?

**Comment by ifedchankau** [comment]
Not actual (#50)
