### ISSUE TITLE
Add new property to configuration

### ISSUE THREAD

**Issue by ifedchankau** [linterhub/usage-parser#79]
Please, add new property "parseWhole" [boolean] to configuration.  

If it true and no sections with names and postfixes was found, the whole file will be parsed. Each part, which starts at new line and begin with "-" will be parsed as option, and part between option and next option will be parsed as option description.

**Comment by romanrostislavovich** [comment]
Property `name`is required in the `section` of configuration. I suggest change it to optional because some `help` don't have any section names

**Comment by ifedchankau** [comment]
@svoboda-rabstvo yes, you are right. I'll change it.

**Comment by romanrostislavovich** [comment]
@Arcle1 don't forget for tests :)
