### ISSUE TITLE
Fixes in parsing

### ISSUE THREAD

**Issue by ifedchankau** [linterhub/usage-parser#82]
I've found next errors:
- when description is fully on next line with option, it is not parsing
- exception when postfix or names [config] is string (not an array)
- parseWhole always changing to default config value

**Comment by romanrostislavovich** [comment]
Name of issue is unclear, please rename it

**Comment by ifedchankau** [comment]
@svoboda-rabstvo yes, but i still haven't finished with tests. It will be clearer later.
