### ISSUE TITLE
Add delimiter parsing by options section

### ISSUE THREAD

**Issue by ifedchankau** [linterhub/usage-parser#90]
Now delimiter is parsing only by examples section. Please, add delimiter parsing by options section.

Example (delimiter `=`):
```
Options:
    -c, --config=<file>
```
Example (delimiter ` `):
```
Options:
    -c, --config <file>
```
Also, add tests for it.

**Comment by romanrostislavovich** [comment]
I'm not sure about this issue, because some options look like: 
```
-c, --config string
-c, -- config : String
```

How tell the difference between additional information and value of the option for identification delimiter?

**Comment by romanrostislavovich** [comment]
I suggest to create separate property in `option` for delimiter

**Comment by romanrostislavovich** [comment]
Please, renemase issue for parsing by `option` section not `example`
