### ISSUE TITLE
Make list of special arguments for prefix configurable

### ISSUE THREAD

**Issue by ifedchankau** [linterhub/usage-parser#96]
Now, list of special arguments (to which custom prefix is adding) is not configurable. 

List of special prefixes:
* version
* help
* config
* stdin
* stdin-filename, stdin-filepath
* path

Users should be able to change this list. Please, make it configurable.

**Comment by romanrostislavovich** [comment]
We remove they in version `2.0.0`, which is next. Can i close the issue?
Ping @Arcle1 | @xferra

**Comment by romanrostislavovich** [comment]
Closed in #174
